### ISSUE TITLE
Clinical Evaluation

### ISSUE THREAD

**Issue by greg-westnine** [eQualityTime/TheOpenVoiceFactory#104]
Something we may have missed in our initial set of tasks, the Med Dev directive, Annex X says"
1.1.1.  Either a critical evaluation of the relevant scientific literature currently available relating to the safety, performance, design characteristics and intended purpose of the device, where:
  — there is demonstration of equivalence of the device to the device to which the data relates, and
  — the data adequately demonstrate compliance with the relevant essential requirements.
1.1.2. Or a critical evaluation of the results of all clinical investigations made.
1.1.3. Or a critical evaluation of the combined clinical data provided in 1.1.1 and 1.1.2."

**Comment by joereddington-public** [comment]
That's doable - are we thinking a page? (It's mostly going to be me citing [these]( http://joereddington.com/researchpublications/))

**Comment by greg-westnine** [comment]
Those references seems like what we're looking for.  I'm not sure the length matters so long as it does point 1.1.1 above
