### ISSUE TITLE
Vocalise Error Messages

### ISSUE THREAD

**Issue by greg-westnine** [eQualityTime/TheOpenVoiceFactory#109]
Error messages are written to the console log and, when #108 is implemented they will be displayed to the board, however they would be even more obvious to the user, and to those around the user if they were vocalised.
"As a user I want error messages to be read out so that I can be immediately aware if there is an issue with processing my board"
and
"As a friend or family member of a user I want error messages to be read out so that I can be immediately aware if there is an issue with the processing of my friend/family member's board and can help them if they require it"

**Comment by joereddington** [comment]
I like the concept here.  (There's a bit of rewritting needed).  Let me ask some users...
