### ISSUE TITLE
Warning for when two pages are called the same label

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/TheOpenVoiceFactory#14]
https://trello.com/c/YqZk0VJQ/74-warning-for-when-two-pages-are-called-the-same-label

**Comment by joereddington-public** [comment]
Okay, so what are the steps here? 

- [ ] Check to see if there is an existing test (the functionality might exist) 
- [ ] branch off 
- [ ] create test 
- [ ] put in functionality 
- [ ] push as feature branch 
- [ ] consider entry to roadmap.

**Comment by joereddington** [comment]
This was dealt with in a recent push.
