### ISSUE TITLE
Android app should import pagesets from URL

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/TheOpenVoiceFactory#49]
The android app needs to be able to load other pagesets. We can do this by simply allowing the user to put in a URL into a dialog box. 

Some suitable test URLs are: 

http://designs.theopenvoicefactory.org/dca992635552539033bdaeff09093bcf/?lang=Laura

http://designs.theopenvoicefactory.org/c7db2730a4451fa10f62c3a1ea81d6c7/?lang=Daniel 

http://equalitytime.github.io/CommuniKate/demos/CK20V2.pptx/

**Comment by joereddington** [comment]
@arpitgoyal2008

**Comment by arpitgoyal2008** [comment]
Hi @joereddington how to extract JSON from the urls above? Is there a mechanism to convert the ids to JSON?

**Comment by joereddington** [comment]
As resulted, 4 by 4 pageset is here: http://equalitytime.github.io/CommuniKate/demos/CK12+V2.pptx/
