### ISSUE TITLE
CK12 loading issue.

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/TheOpenVoiceFactory#5]
From email Sun, Jan 29, 2017 at 8:00 AM.  

Page NOT found. (details in Joe's email)

**Comment by joereddington** [comment]
[CK12+V2+edited.pptx](https://github.com/eQualityTime/TheOpenVoiceFactory/files/744938/CK12.V2.edited.pptx)

This is the file that shows an example of the problem.

**Comment by joereddington** [comment]
ht: @neilt17

**Comment by joereddington** [comment]
###### 11/02/2017-13:42:19 GMT:
Okay, let's have a look. 

###### 11/02/2017-13:42:26 GMT:
Two things to check - first that we get the same behaviour thought the web app, and then that we get the same behaviour locally. 

###### 11/02/2017-13:43:26 GMT:
Uploading now. 

###### 11/02/2017-13:44:05 GMT:
Yep, issue is repeatable... (via http://designs.theopenvoicefactory.org/70f4fba5a97ea5af6ce0d2c24f0f2a52/?lang=Daniel) 

error message in console is:     
     
     http://designs.theopenvoicefactory.org/70f4fba5a97ea5af6ce0d2c24f0f2a52/pageset.json Failed to load resource: the server responded with a status of 404 (Not Found)


###### 11/02/2017-13:44:45 GMT:

###### 11/02/2017-13:46:36 GMT:
Running locally. 


###### 11/02/2017-13:47:30 GMT:
Error locally is: 
```
Traceback (most recent call last):
  File "grab_text.py", line 379, in <module>
    grids = extract_and_label_images(prs, grids, dest)
  File "grab_text.py", line 339, in extract_and_label_images
    export_images(grids, image_slight_number, slide, filename, SAVE)
  File "grab_text.py", line 247, in export_images
    for shape in images[x, y]])
  File "/Library/Python/2.7/site-packages/pptx/util.py", line 175, in get_prop_value
    value = f(obj)
  File "/Library/Python/2.7/site-packages/pptx/parts/image.py", line 264, in size
    return self._pil_props[1]
  File "/Library/Python/2.7/site-packages/pptx/util.py", line 175, in get_prop_value
    value = f(obj)
  File "/Library/Python/2.7/site-packages/pptx/parts/image.py", line 280, in _pil_props
    pil_image = PIL_Image.open(stream)
  File "/Library/Python/2.7/site-packages/PIL/Image.py", line 2286, in open
    % (filename if filename else fp))
IOError: cannot identify image file <StringIO.StringIO instance at 0x10f120290>
MacBook-Air:openvoicefactory josephreddington$ open grab_text.py
```

###### 11/02/2017-13:47:57 GMT:
That "IOError: cannot identify image file <StringIO.StringIO instance at 0x10f120290>" looks like a good place to start. 

###### 11/02/2017-13:52:15 GMT:
Google is recommending upgrading Pillow. I'll give that a go to eliminate it from the options... 

###### 11/02/2017-13:54:47 GMT:
It's upgraded. Running again... 

###### 11/02/2017-13:55:57 GMT:
Ah-ha - it gives an error, so that's an inprovement. Now it just refuses to give me the image in quesiton.   So there are two things to do here. One is to upgrade the pillow on the server, and the next is to continue investigating the bug itself. 

###### 11/02/2017-13:59:53 GMT:
(and indeed, dreamhost refuses the install privledges so it might be a problem to get that working...) 

###### 11/02/2017-14:01:04 GMT:
My new error message is: 

```
cannot find loader for this WMF file
```

###### 11/02/2017-14:07:51 GMT:
Hmmm, some interneting [suggests](http://stackoverflow.com/questions/14103891/convert-emf-wmf-files-to-png-jpg) that this error is caused by PowerPoint using a windows only format.  It looks like the best I can do is produce a decent error message... 

###### 11/02/2017-14:15:44 GMT:
Think i've done that... let's see. I'm going to push to testing. (the comitt is a77ee47b830e8308e57da3e37c6e9ddeef2c4e5c) 

###### 11/02/2017-14:20:53 GMT:
Hmm... didn't work on test... that's odd.. 

###### 11/02/2017-14:22:12 GMT:
Trying a 'standard' pageset to see what's happening... 

###### 11/02/2017-14:29:22 GMT:
That worked, so I've expanded the exception handling - increasingly difficult to code when the sever isn't up to date... 

###### 11/02/2017-14:31:39 GMT:
Doing some editing on the testing server. 

###### 11/02/2017-14:33:09 GMT:
Working live, but it's NOT giving the same error message.. .

###### 11/02/2017-14:34:26 GMT:
I've edited to get the error message working.  

###### 11/02/2017-14:36:00 GMT:
Fixing an output issue while I'm there

###### 11/02/2017-14:38:57 GMT:
Not quite fixed, but at least this is happening... 
![screen shot 2017-02-11 at 14 38 50](https://cloud.githubusercontent.com/assets/4369547/22854505/dd60e816-f067-11e6-9c22-c41cb31a6991.png)


###### 11/02/2017-14:40:41 GMT:
Trying again now. 

###### 11/02/2017-14:40:46 GMT:
And works! 
![screen shot 2017-02-11 at 14 40 29](https://cloud.githubusercontent.com/assets/4369547/22854514/16a0c1b4-f068-11e6-9c8c-eea26eb05086.png)

###### 11/02/2017-14:40:56 GMT:
Time to bring that over into the master branch 

###### 11/02/2017-14:42:21 GMT:
I've merged. One last test. 

###### 11/02/2017-14:43:16 GMT:
Okay, now for the master 

###### 11/02/2017-14:44:27 GMT:
It's been pulled. Testing...

![screen shot 2017-02-11 at 14 45 03](https://cloud.githubusercontent.com/assets/4369547/22854538/b0d13a48-f068-11e6-87cd-bcaaeea06a13.png)


###### 11/02/2017-14:46:52 GMT:
Now that the error is dealt with, let's try a workaround.  I'm using the standard 'save as picture' approach. 

![screen shot 2017-02-11 at 14 46 10](https://cloud.githubusercontent.com/assets/4369547/22854560/27742bd8-f069-11e6-850b-a78d88e4281a.png)


###### 11/02/2017-14:49:01 GMT:
Score! Availible [here](http://designs.theopenvoicefactory.org/dc66606089ac0edd05bd09e3715fa490/?lang=Daniel) 
![screen shot 2017-02-11 at 14 48 54](https://cloud.githubusercontent.com/assets/4369547/22854562/402269b0-f069-11e6-9918-3e96b8cc31c5.png)

###### 11/02/2017-14:49:25 GMT:
I'm adding a task to email the guy, and closing this.

**Comment by neilt17** [comment]
Great - I've tried uploading the same file again and it now works.
