### ISSUE TITLE
Bug: Links failing on Android app.

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/TheOpenVoiceFactory#51]
@arpitgoyal2008  Links are taking the user to the wrong page at the current build.    E.g. 'chatting' is going to the 'drinks description' page. And the 'Top page' takes users to the 'snacks' page.

**Comment by joereddington** [comment]
Edit - this only occurring when a new pageset is loaded via the URL (in this example it was http://designs.theopenvoicefactory.org/7cc3961352b62288c69139f94387c2f6/?lang=Daniel)

**Comment by arpitgoyal2008** [comment]
I am not able to reproduce this issue at my end. Can you check once again?

**Comment by joereddington** [comment]
I'll make a video, but I'll check the new APK first in case something else changed :)

**Comment by joereddington** [comment]
Indeed, I am unable to reproduce on the new APK.  Closing. :)

**Comment by arpitgoyal2008** [comment]
Great. If you encounter this again, I would debug again.
