### ISSUE TITLE
Move Web app to OBF

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/TheOpenVoiceFactory#65]
Our current Javascript was written by me and is shoddy in a number of ways.  It's also missing a few features. 

One of the big features we need is compatibility with [OBF](http://www.openboardformat.org/).  In particular the (potentially slightly wrong) OBF that we have generate from the python.

So the task is: using Test Driven Developement (I like Karma for Javascript testing, but I'm open), write the javascript that parses [this OBZ file](https://openboards.s3.amazonaws.com/examples/communikate-20.obz) and puts it into the right datastructures for the webapp.  The old parse-and-populate snippet in https://github.com/eQualityTime/TheOpenVoiceFactory/blob/master/templates/javascript/read_json.js is    

```
function setupInternalDataStructures(responseText){
	    key = "toppage";
	    utterances = {};
	    links = {};
	    colours = {};
	    icons = {};
	    labels = {};
	    slide_number = {};

            var obj = JSON.parse(responseText);
            for (grid in obj.Grid) {
                console.log(obj.Grid[grid][0])
                labels[obj.Grid[grid][0]] = obj.Grid[grid][1];
                utterances[obj.Grid[grid][0]] = obj.Grid[grid][2];
                links[obj.Grid[grid][0]] = obj.Grid[grid][3];
                icons[obj.Grid[grid][0]] = obj.Grid[grid][4];
                colours[obj.Grid[grid][0]] = obj.Grid[grid][5];
                slide_number[obj.Grid[grid][0]] = obj.Grid[grid][6];
                if (obj.Grid[grid][6] == 0) {
                    key = obj.Grid[grid][0]
                }
            }
            grid_size_rows = obj.Settings[0];
            grid_size_columns = obj.Settings[0];

}

```

**Comment by joereddington** [comment]
I want to have a conversation with Shay about this.  Apps come first.

**Comment by joereddington-public** [comment]
Have reviewed pull request from @balvinderimpinge - looks fine, I haven't approached the pull tho, because it was to the master branch rather than the ovfinput branch.  A quick correction should sort that out.  :)

**Comment by joereddington** [comment]
Having a problem running tests,  what am I missing? 

```
MacBook-Air:templates josephreddington$ pwd
/Users/josephreddington/Dropbox/git/openvoicefactory/templates
MacBook-Air:templates josephreddington$ git pull
Already up to date.
MacBook-Air:templates josephreddington$ git status
On branch ovfinput
Your branch is up to date with 'origin/ovfinput'.

Untracked files:
  <snip>

nothing added to commit but untracked files present (use "git add" to track)
MacBook-Air:templates josephreddington$ karma start karma.conf.js 
09 07 2018 17:07:24.728:WARN [karma]: No captured browser, open http://localhost:9876/
09 07 2018 17:07:24.753:INFO [karma]: Karma v1.3.0 server started at http://localhost:9876/
09 07 2018 17:07:24.756:INFO [launcher]: Launching browser Chrome with unlimited concurrency
09 07 2018 17:07:24.784:INFO [launcher]: Starting browser Chrome
09 07 2018 17:07:27.277:INFO [Chrome 67.0.3396 (Mac OS X 10.13.4)]: Connected on socket /#dtetCL0B7AzycmT9AAAA with id 88303081
09 07 2018 17:07:27.475:WARN [web-server]: 404: /base/sampledata/test-1.obf?_=1531152447446
Chrome 67.0.3396 (Mac OS X 10.13.4) ERROR
  Uncaught SyntaxError: Unexpected token o in JSON at position 1
  at http://localhost:9876/context.html:1
Chrome 67.0.3396 (Mac OS X 10.13.4): Executed 0 of 4 ERROR (0.024 secs / 0 secs)
```

**Comment by balvinderimpinge** [comment]
@joereddington 

I have figure out why the test cases are not working on your machine. For this I have fixed something in the code. Please use the latest code. When you get the new code please try this.
1) go to templates folder
2) run "npm install" command
3) run npm test

I hope after that you will get the test cases working correctly.

**Comment by joereddington-public** [comment]
Hi @balvinderimpinge - I tried this and ran into a slight problem - fortunately I was streaming at the time, so I have a video for you - https://www.twitch.tv/videos/283770978?t=00h24m39s. Helpfully this means I was also downloading to a new user account and doing everything from scratch (just like a new contributor would).

**Comment by balvinderimpinge** [comment]
Hi @joereddington - 

I have checked your video and I have seen you follow the above instructions that I have mentioned. But after that the test cases still not working. 
Actually, When I saw your video I have noticed that you are using NodeJS version 0.12.2 and this is very old version and right now  most of the node modules not support on this version. Now NodeJS released the 10.6.0. 
Also, have you notice when you install the NodeJS module using "npm install" command it gives warning message regarding the NodeJS required version and also show you the current version?

So, I suggest you please upgrade the NodeJS and npm packages to latest one at least version 8 check this link https://nodejs.org/en/. After that repeat the same step that I have mentioned above.

Thanks

**Comment by joereddington-public** [comment]
Success! (well, 2 failures, but the tests are running.  Thank you Balvinder.

**Comment by joereddington-public** [comment]
I'm going to close this because it's being supplanted by other issues, and I'll make it into a overarching project.
