### ISSUE TITLE
Open Voice Factory Displays a single page from an OBF document 

### ISSUE THREAD

**Issue by joereddington-public** [eQualityTime/TheOpenVoiceFactory#74]
As a system, I want to render a single page from an OBF file so that the page is correctly displayed to the user.

As a milestone in the introduction of OBF it would be good to see a single page of OBF rendered in the app.  I'd like to use the main page, but others are find. It should look at lot like this: 

![screen shot 2018-07-16 at 17 21 19](https://user-images.githubusercontent.com/40637406/42770545-cdbd9982-891c-11e8-891e-6b4bbd322abb.png)

(cc @greg-westnine (for some reason I can't tag B))

**Comment by joereddington** [comment]
Merged - for completeness, can we have some instruction on how to demonstrate the behaviour?

**Comment by joereddington-public** [comment]
Done per https://github.com/eQualityTime/TheOpenVoiceFactory/pull/94 (and apparently a duplicate of #79...)
