### ISSUE TITLE
read_json refactoring

### ISSUE THREAD

**Issue by greg-westnine** [eQualityTime/TheOpenVoiceFactory#76]
In order to better support unit testing, some refactoring of read_json would be beneficial, in particular:
- Separation of logic from display functionality
- Reduce embedding of literals and use constants instead
- Reduce use of global variables

**Comment by balvinderimpinge** [comment]
Here is updated document. In this document I have mentioned how we will write the code.
[document.txt](https://github.com/eQualityTime/TheOpenVoiceFactory/files/2486870/document.txt)
