### ISSUE TITLE
Open new obf page from link

### ISSUE THREAD

**Issue by greg-westnine** [eQualityTime/TheOpenVoiceFactory#79]
As a system I want to load and display a new obf page when the appropriate cell is selected from the currently loaded obf page, so that I can render nested pages.

This is linked to issue  #78

**Comment by joereddington-public** [comment]
###### 21/08/18 10:56: 
I'm going to take a swing at this today.

**Comment by joereddington-public** [comment]
This is complete as per https://github.com/eQualityTime/TheOpenVoiceFactory/pull/94
