### ISSUE TITLE
Create a Manifest file for OVF format files

### ISSUE THREAD

**Issue by greg-westnine** [eQualityTime/TheOpenVoiceFactory#80]
When OVF files are created, a new manifest.json file should be created as well to tell read_json to parse the file as ovf.
Correct format will be added shortly.

# Plan 
- [ ] write tests 
- [ ] implement 
- [ ] Make sure we are following the proper process (which means pull request) 
- [ ] Also upload a number of results files (zip 'em)

**Comment by greg-westnine** [comment]
{
  "format": "open-board-0.1",
  "root": "boards/my-board.ovf"  
}

This is the same format as the manifest.json file for OBF boards.

**Comment by joereddington-public** [comment]
There's now a pull request - @greg-westnine  to review.

**Comment by joereddington-public** [comment]
Hi @greg-westnine  did you get a chance to look at the pull request?

**Comment by joereddington** [comment]
(agreed with greg)  - but need to alter  policies as well.
