### ISSUE TITLE
Create Detailed Device Description

### ISSUE THREAD

**Issue by greg-westnine** [eQualityTime/TheOpenVoiceFactory#82]
As part of our medical device registration we are required to produce a Device Description.

To include:
- Intended use
- Nature and Function of the system
- How the system is to be used, what equipment (hardware) and dependent software is required
- Specific conditions the system supports
- Class (I)

From our resources: 

> The STED should include the following device descriptive information:
> a)	the intended use of the IVD medical device.  This may include:
> 1)	what is detected
> 2)	its function (e.g. screening, monitoring, diagnosis or aid to diagnosis);
> 3)	the specific disorder, condition or risk factor of interest that it is intended to detect, define or differentiate;
> 4)	whether it is automated or not; 
> 5)	whether it is qualitative or quantitative; 
> 6)	the type of specimen(s) required (e.g. serum, plasma, whole blood, tissue biopsy, urine); 
> 7)	testing population; 
> b)	the intended user (lay person or professional);
> c)	a general description of the principle of the assay method or instrument principles of operation;
> d)	the Class of the device and the applicable classification rule according to Principles of In Vitro Diagnostic Medical Devices Classification ;
> e)	a description of the components (e.g. reagents, assay controls and calibrators) and where appropriate, a description of the reactive ingredients of relevant components (such as antibodies, antigens, nucleic acid primers).

**Comment by greg-westnine** [comment]
@joereddington how's this?
[Device.Description.v0.1.docx](https://github.com/eQualityTime/TheOpenVoiceFactory/files/2388970/Device.Description.v0.1.docx)

**Comment by joereddington-public** [comment]
Looks good.  I've done some very minor tidying up.  For the benefit of the casual reader - here's the definition of 'Active Theraputic Device', which I suspect that technically we are.  

![screen shot 2018-09-20 at 08 54 50](https://user-images.githubusercontent.com/40637406/45804006-df382780-bcb2-11e8-8fab-9a03f7e1ea6e.png)
[Device.Description.v0.2.docx](https://github.com/eQualityTime/TheOpenVoiceFactory/files/2400291/Device.Description.v0.2.docx)

Greg - what do you think the next actions are on this?

**Comment by greg-westnine** [comment]
I have done some further tweaks, and added the requirements and profiles from the wiki.  I've added what we have the architecture (some bits are missing) and an example.

[Device.Description.v0.3.docx](https://github.com/eQualityTime/TheOpenVoiceFactory/files/2400769/Device.Description.v0.3.docx)

**Comment by greg-westnine** [comment]
Now I'm thinking about the statements we need to make about the environment in which OVF runs.  As I see it there are two main things to think about:

1. The user's device
1. The OVF webserver
It is possible for a user to run OVF entirely on their own machine, or they may access OVF from the eQualityTime servers.

In the first instance, we need to stipulate what browsers we support, what operating systems, what webserver, particular versions of these components we will/wont support and any other factors relating to the local user's environment.

In the second instance we need to stipulate what operating system and webserver we offer, what the hosting environment is and how we control it's configuration.  We also need to indicate how we ensure that this environment is, and remains operational, and what availablity we guarantee.

**Comment by joereddington-public** [comment]
> In the first instance, we need to stipulate what browsers we support, what operating systems, what webserver, particular versions of these components we will/wont support and any other factors relating to the local user's environment.

I've written in some (relatively restrictive) system requirements on the principle that makes it a lot easier for us to test them. 

> In the second instance we need to stipulate what operating system and webserver we offer, what the hosting environment is and how we control it's configuration. We also need to indicate how we ensure that this environment is, and remains operational, and what availablity we guarantee.

I can get some technical specs from dreamhost 


I've given the whole document a review and done: 

- System requirements for the local instance 
- Some work on the architecture for the upload side 
- General reformating and a table of contents (mostly so I can see the structure) 

I've added a bunch of comments in the process mostly questions about best way to structure an argument.  There's probably more I can do on this, but I'd like to hand it back to look at the rest of the issues.   

Next action is for someone else (@greg-westnine ideally) to go through and answer the questions/rewrite. 
[Device.Description.v0.4.docx](https://github.com/eQualityTime/TheOpenVoiceFactory/files/2436965/Device.Description.v0.4.docx)

**Comment by joereddington-public** [comment]
ha! Just found this handy diagram in the wiki: https://github.com/eQualityTime/TheOpenVoiceFactory/wiki/Architecture-Upload-Physical we should probably put that in...

**Comment by greg-westnine** [comment]
Updated and cleaned up a bit.
[Device.Description.v0.5.docx](https://github.com/eQualityTime/TheOpenVoiceFactory/files/2446728/Device.Description.v0.5.docx)

**Comment by joereddington** [comment]
Next action for Joe to review.

**Comment by joereddington-public** [comment]
I have reviewed and the reviewed file is in the [MHRA repository](https://github.com/eQualityTime/MHRA-Technical-File)

**Comment by joereddington-public** [comment]
I'm happy to recommend closing this isssue - a file has been created, and it probably wants to be reviewed later on as part of the whole package...
