### ISSUE TITLE
Snapshot of Risk Register

### ISSUE THREAD

**Issue by greg-westnine** [eQualityTime/TheOpenVoiceFactory#83]
Include a summary and the list of risks and mitigations at the time of creation of the technical file.

Related #100 

# Plan 
- [ ] Check the existing document complies with our own risk policy, 
- [ ] actually issue it as a 1.0 document.

**Comment by joereddington** [comment]
Next action: check that it complies with our own policy FFS. And if it does, mark as done.  Maybe make slightly prettier.

**Comment by greg-westnine** [comment]
Having updated the Risk Policy, we now need to create a Risk Plan for OVF, a draft of which is here:
[TheOpenVoiceFactory Risk Plan v0-1.docx](https://github.com/eQualityTime/TheOpenVoiceFactory/files/2400904/TheOpenVoiceFactory.Risk.Plan.v0-1.docx)

**Comment by greg-westnine** [comment]
Also following on from the update of the Risk Policy, I have updated the Risk Register.  It no longer fits in a document so have switched to xls.  There is a case for using Google Sheets for improved collaboration.  What do you think @joereddington 
[OVF.risk_.assessment.v0.4.xlsx](https://github.com/eQualityTime/TheOpenVoiceFactory/files/2400925/OVF.risk_.assessment.v0.4.xlsx)

**Comment by joereddington-public** [comment]
Some edits - mostly approving the risk plan as the product owner and adding a controlled document sheet to the excel. 

On Google Sheets - I'm generally in favour of google drive (we use it for http://whitewaterwriters.com/) but I'm also against mixing too many formats in one project... 

On the risk assessment - lots of these are starting to be outside of our control. I'm a little worried that we are taken on responsbilities that we don't need (also, for many of them, it ends up being 'write in the manual that you should have suitable battery levels').    Is there much guidance on what should and shouldn't be in a risk assessment? I'm sort of asking if we can factor out some of the text.  (I.e - can we have a page of on the help files saying "Make sure that the volume is turned up and the battery is fully charged on your device before using open voice factory" and then a risk of 'user doesn't follow startup instructions?'?


[OVF.risk_.assessment.v0.5.xlsx](https://github.com/eQualityTime/TheOpenVoiceFactory/files/2437133/OVF.risk_.assessment.v0.5.xlsx)
[TheOpenVoiceFactory.Risk.Plan.v1.0.docx](https://github.com/eQualityTime/TheOpenVoiceFactory/files/2437134/TheOpenVoiceFactory.Risk.Plan.v1.0.docx)

**Comment by joereddington** [comment]
Medidum | Device Fails completely
-- | --
High | Device causes active harm
Low | Device has interminent and annoying fault

**Comment by joereddington** [comment]
We've now filled out the document properly, and it lives here: https://github.com/eQualityTime/MHRA-Technical-File/blob/master/OVF.risk_.assessment.xlsx
