### ISSUE TITLE
Statement of Essential Principles

### ISSUE THREAD

**Issue by greg-westnine** [eQualityTime/TheOpenVoiceFactory#85]
For our medical device registration we require a statement of Essential Principles. 

There is a sample table on p28 of this: 
[Summary.of.Technical.Documentation.Conformity.docx](https://github.com/eQualityTime/TheOpenVoiceFactory/files/2370952/Summary.of.Technical.Documentation.Conformity.docx)

This issue is to produce a completed version of that table relevent to the open voice factory on EQT headed paper. 

Oh but wait: 

> .  The Essential Principles listed in the first column should be extracted from the latest version of the GHTF’s guidance document Essential principles of Safety and Performance of Medical Devices”.  Those incorporated into this document are extracted from GHTF/SG1/N41:2005.

So the next action is to find the most recent version.

**Comment by joereddington-public** [comment]
I went throught quite a lot of work to discover that http://www.imdrf.org/docs/ghtf/final/sg1/technical-docs/ghtf-sg1-n011-2008-principles-safety-performance-medical-devices-080221.pdf is the most recent of the GHTF (which has been replaced) documentation.

**Comment by joereddington-public** [comment]
I did the copy paste and spent some time removing useless formating.  Looking at it, I think I need @greg-westnine  to take the first pass... 
[Statement of Essential Principles.v.0.1.docx](https://github.com/eQualityTime/TheOpenVoiceFactory/files/2400483/Statement.of.Essential.Principles.v.0.1.docx)


A note as a quote

> The STED should contain an EP checklist that identifies:-
> a)	the Essential Principles;
> b)	whether each Essential Principle applies to the device and if not, why not;
> c)	the method(s) used to demonstrate conformity with each Essential Principle that applies; 
> d)	a reference for the method(s) employed (e.g., standard), and
> e)	the precise identity of the controlled document(s) that offers evidence of conformity with each method used.
> 
> Methods used to demonstrate conformity may include one or more of the following:
> a)	conformity with recognised or other standards ;
> b)	conformity with a commonly accepted industry test method(s); 
> c)	conformity with an in-house test method(s);
> d)	the evaluation of pre-clinical and clinical evidence .
> e)	comparison to a similar device already available on the market.

**Comment by joereddington-public** [comment]
@greg-westnine - are you okay taking a pass at this?

**Comment by joereddington-public** [comment]
Hey Greg - some of these appear to have arrived in https://github.com/eQualityTime/TheOpenVoiceFactory/issues/89 - is that as part of a summary? Or is it worth combining the two?
