### ISSUE TITLE
System Requirements

### ISSUE THREAD

**Issue by greg-westnine** [eQualityTime/TheOpenVoiceFactory#86]
For medical device registration we require a nicely formatted document of the requirements that users have of the system, in our case we are repesenting those by user stories [here](https://github.com/eQualityTime/TheOpenVoiceFactory/wiki/OpenVoiceFactory-Requirements) and they can be put into a pretty pdf (and controlled document) 

There would be NO harm in adding the user personals from #96 once finnished.

**Comment by joereddington-public** [comment]
For what it's worth - I've updated https://github.com/eQualityTime/TheOpenVoiceFactory/wiki/OpenVoiceFactory-Requirements to include the personas.  If we are okay to copy and paste that page then we're in good shape.  Are we okay to do that?

**Comment by greg-westnine** [comment]
Looks good.  Can you expand CIA?  I'm not familiar with the term.
I've added a link to CK12 and CK20 at the bottom.
I agree we can copy this into the Device Description, which I will do now since I am making some other updates.  We will need to keep an eye on version control though, if this description is further changed before we submit our technical file.

**Comment by joereddington** [comment]
That's a typo.  Should be 'via'.

**Comment by joereddington-public** [comment]
To check a mild confusion of mine - wouldn't we copy it into the System requirements? Or have I got lost...

**Comment by joereddington-public** [comment]
If that works for you, it works for me. I think you've already moved the content over to #82 anyway - is the next action to close this issue and do the work there?
