### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by greg-westnine** [eQualityTime/TheOpenVoiceFactory#87]
The medical device registration requires that we include an example of our Release Notes for a release as evidence that we produce them.    Template for release notes should be in producer developed in https://github.com/eQualityTime/Public/issues/7.

**Comment by joereddington** [comment]
Next action is to do a release and make sure we do it properly.

**Comment by joereddington-public** [comment]
@greg-westnine  - I think you mentioned you'd put up a template release somewhere - have I got lost?
