### ISSUE TITLE
Fix failing test in the python.

### ISSUE THREAD

**Issue by joereddington-public** [eQualityTime/TheOpenVoiceFactory#92]
### Summary 
Test failing in production branch

### Steps to reproduce 
Run 

    python test_grab_text.py ovfTest.test_create_obf_object

in the 'tests' directory of the repo. 

### Expected Results 
The obj object produced by these lines:

        grids = self.get_singleton_CK20().grids
        obf=grab_text.create_obf_object(grids[0])
 
Should match this file (when unzipped). 
[singleobffile.obf.zip](https://github.com/eQualityTime/TheOpenVoiceFactory/files/2305169/singleobffile.obf.zip)

### Actual Results
It does not.  The issue appears to be a difference in quotation marks.  (running opendiff temp.json ../testoutputs/singleobffile.obf  after testing only this case)

![screen shot 2018-08-21 at 08 10 42](https://user-images.githubusercontent.com/40637406/44386240-d91b2380-a519-11e8-8370-895559de95bd.png)

**Comment by greg-westnine** [comment]
@joereddington if we are following the policy, this is a bug, and should have that label.  It should say what the bug is, ie expected behaviour and actual behaviour.

**Comment by joereddington-public** [comment]
Okay, first todo item is check what OBF actually wants - is it single or double quotes? 

From [SE](https://stackoverflow.com/a/14355677) "As per the API documentation, double quotes are considered valid JSON, single quotes aren't." 

We should do a bit more work and check that obf wants to be valid json...
